### ISSUE TITLE
vllm  Qwen1.5-14B-Chat-GPTQ-Int4 error

### ISSUE THREAD

**Issue by allenhaozi** [QwenLM/Qwen1.5#106]
use vllm serving  occur the following errors:

```
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
```

```
+ python3 -m vllm.entrypoints.openai.api_server --host x.x.x.x --port 8000 --served-model-name qwen1.5-14b-chat-int4 --model /home/vllm/model/Qwen1.5-14B-Chat-GPTQ-Int4 --trust-remote-code --chat-template {% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %} --tokenizer-mode auto --max-num-batched-tokens 32768 --tensor-parallel-size 2
INFO 02-29 13:47:41 api_server.py:228] args: Namespace(host='x.x.x.x', port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name='qwen1.5-14b-chat-int4', lora_modules=None, chat_template="{% for message in messages %}{{'<|im_start|>' + message['role'] + '\\n' + message['content'] + '<|im_end|>' + '\\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\\n' }}{% endif %}", response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='/home/vllm/model/Qwen1.5-14B-Chat-GPTQ-Int4', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=32768, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 02-29 13:47:42 config.py:186] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 02-29 13:47:42 config.py:421] Custom all-reduce kernels are temporarily disabled due to stability issues. We will re-enable them once the issues are resolved.
2024-02-29 13:47:45,191 INFO worker.py:1724 -- Started a local Ray instance.
INFO 02-29 13:47:48 llm_engine.py:87] Initializing an LLM engine with config: model='/home/vllm/model/Qwen1.5-14B-Chat-GPTQ-Int4', tokenizer='/home/vllm/model/Qwen1.5-14B-Chat-GPTQ-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=True, quantization=gptq, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 236, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 625, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 366, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 126, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/engine/llm_engine.py", line 306, in _init_workers_ray
    self._run_workers(
  File "/workspace/vllm/engine/llm_engine.py", line 1036, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/workspace/vllm/worker/worker.py", line 100, in load_model
    self.model_runner.load_model()
  File "/workspace/vllm/worker/model_runner.py", line 88, in load_model
    self.model = get_model(self.model_config,
  File "/workspace/vllm/model_executor/utils.py", line 52, in get_model
    return get_model_fn(model_config, device_config, **kwargs)
  File "/workspace/vllm/model_executor/model_loader.py", line 79, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/workspace/vllm/model_executor/models/qwen2.py", line 276, in __init__
    self.model = Qwen2Model(config, linear_method)
  File "/workspace/vllm/model_executor/models/qwen2.py", line 238, in __init__
    self.layers = nn.ModuleList([
  File "/workspace/vllm/model_executor/models/qwen2.py", line 239, in <listcomp>
    Qwen2DecoderLayer(config, layer_idx, linear_method)
  File "/workspace/vllm/model_executor/models/qwen2.py", line 182, in __init__
    self.mlp = Qwen2MLP(
  File "/workspace/vllm/model_executor/models/qwen2.py", line 67, in __init__
    self.down_proj = RowParallelLinear(intermediate_size,
  File "/workspace/vllm/model_executor/layers/linear.py", line 494, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/workspace/vllm/model_executor/layers/quantization/gptq.py", line 100, in create_weights
    raise ValueError(
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
```

**Comment by huangyunxin** [comment]
14B只能单卡部署 https://github.com/QwenLM/Qwen1.5/issues/63

**Comment by allenhaozi** [comment]
> 14B只能单卡部署 #63
Thank you for your reply, succeeded with a single card
