### ISSUE TITLE
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

### ISSUE THREAD

**Issue by peakji** [QwenLM/Qwen1.5#11]
When deploying `Qwen/Qwen1.5-0.5B-Chat-GPTQ-Int4` with vLLM v0.3.0, calling it via cURL as shown in [README.md](https://github.com/QwenLM/Qwen1.5?tab=readme-ov-file#vllm) will result in the following error.

If `stream=true` is used, there won't be an error, but the output will be a series of "!" tokens. It seems like there is an error related to the vocabulary while decoding.

It's worth mentioning that the error only occurs in the 0.5B version; for other GPTQ Int4 versions like 1.8B, 4B, and 7B, this error does NOT occur.

```
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f5e8e5380d0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f5e8bdd2e90>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f5e8e5380d0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f5e8bdd2e90>)>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 29, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 409, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 388, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 203, in step_async
    return self._process_model_outputs(output, scheduler_outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 715, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 586, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 891, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 221, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'
```

**Comment by kyang888** [comment]
@peakji  I have same problem. But Qwen/Qwen1.5-4B-Chat has no problem.

**Comment by jklj077** [comment]
closed in favor of https://github.com/QwenLM/Qwen1.5/issues/122
