### ISSUE TITLE
Lora微调100%，但finetune.py的367行trainer.save_state() 报错TypeError: Object of type Tensor is not JSON serializable

### ISSUE THREAD

**Issue by trunks023** [QwenLM/Qwen1.5#118]
```shell
{'loss': 0.1874, 'grad_norm': tensor(0.0652, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.88}                                                                                                                                       
{'loss': 0.1821, 'grad_norm': tensor(0.0863, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.9}                                                                                                                                        
{'loss': 0.1738, 'grad_norm': tensor(0.0878, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.91}                                                                                                                                       
{'loss': 0.1805, 'grad_norm': tensor(0.0728, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.93}                                                                                                                                       
{'loss': 0.1854, 'grad_norm': tensor(0.0589, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.94}                                                                                                                                       
{'loss': 0.187, 'grad_norm': tensor(0.0700, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.96}                                                                                                                                        
{'loss': 0.1832, 'grad_norm': tensor(0.0592, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.98}                                                                                                                                       
{'loss': 0.1793, 'grad_norm': tensor(0.0589, device='cuda:0'), 'learning_rate': 0.0003, 'epoch': 0.99}                                                                                                                                       
{'train_runtime': 86.6029, 'train_samples_per_second': 11.547, 'train_steps_per_second': 0.716, 'train_loss': 0.5539407564267036, 'epoch': 0.99}                                                                                             
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [01:26<00:00,  1.40s/it]
Traceback (most recent call last):
  File "/output/Qwen1.5/examples/sft/finetune.py", line 375, in <module>
    train()
  File "/output/Qwen1.5/examples/sft/finetune.py", line 367, in train
    trainer.save_state()
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 1045, in save_state
    self.state.save_to_json(path)
  File "/usr/local/lib/python3.10/site-packages/transformers/trainer_callback.py", line 113, in save_to_json
    json_string = json.dumps(dataclasses.asdict(self), indent=2, sort_keys=True) + "\n"
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
[2024-03-04 08:43:32,069] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 771) of binary: /usr/local/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
```

**Comment by o-github-o** [comment]
使用https://github.com/QwenLM/Qwen/blob/main/finetune.py 和qlora微调遇到了相同的保存问题

**Comment by timacro** [comment]
deepspeed 的版本过高， 改成 `pip install deepspeed==0.13.1`

**Comment by timacro** [comment]
deepspeed 的版本过高， 改成 `pip install deepspeed==0.13.1`

**Comment by trunks023** [comment]
> deepspeed 的版本过高， 改成 `pip install deepspeed==0.13.1`

是的，更换版本后，解决了这个问题，感谢大佬！

**Comment by richardodliu** [comment]
> deepspeed 的版本过高， 改成 `pip install deepspeed==0.13.1`

在Qwen的仓库里面看到了一个对应的问题：
(https://github.com/QwenLM/Qwen/issues/1115#issuecomment-1987044787)

似乎这个问题是由于transformers的trainer类的_maybe_log_save_evaluate方法出现问题，所以最好的办法应该还是修改trainer类。
不清楚大佬这里为什么建议降级deepspeed，我没有尝试这个方案，但是我觉得这个似乎并不是这个问题的根本所在，如果大佬有关于这个解决方案的思路，可以在这里说明一下吗？感谢回答

**Comment by mgw2168-1** [comment]
> > deepspeed 的版本过高， 改成 `pip install deepspeed==0.13.1`
> 
> 是的，更换版本后，解决了这个问题，感谢大佬！

问下大佬微调2.5的数据集格式啥样的，还是1的格式吗还是llama-factory里面的格式？
