### ISSUE TITLE
[BUG] AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream'<title>

### ISSUE THREAD

**Issue by newstargo** [QwenLM/Qwen1.5#149]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Welcome to use Qwen-Chat model, type text to start chat, type :h to show command help.
(欢迎使用 Qwen-Chat 模型，输入内容即可进行对话，:h 显示命令帮助。)

Note: This demo is governed by the original license of Qwen.
We strongly advise users not to knowingly generate or allow others to knowingly generate harmful content, including hate speech, violence, pornography, deception, etc.
(注：本演示受Qwen的许可协议限制。我们强烈建议，用户不应传播及不应允许他人传播以下内容，包括但不限于仇恨言论、暴力、色情 、欺诈相关的有害信息。)

User>
[ERROR] Query is empty
User> d
Traceback (most recent call last):
  File "D:\Qwen\cli_demo.py", line 210, in <module>
    main()
  File "D:\Qwen\cli_demo.py", line 198, in main
    for response in model.chat_stream(tokenizer, query, history=history, generation_config=config):
  File "C:\Users\nsg\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat_stream'

### 期望行为 | Expected Behavior

请问如何修复？

### 运行环境 | Environment

```Markdown
- OS:windows 10
- Python:3.10
- Transformers:4.37
- PyTorch:2.2.1
- CUDA 12.2
```

**Comment by jklj077** [comment]
closed as duplicate of https://github.com/QwenLM/Qwen1.5/issues/38
