### ISSUE TITLE
qwen1.5-14b-chat model has not layer_norm_epsilon

### ISSUE THREAD

**Issue by ArlanCooper** [QwenLM/Qwen1.5#153]
当我在使用qwen1.5-14b-chat模型的时候，调用过程中没有相关参数:
```
hf_config = AutoConfig.from_pretrained(
            'qwen/Qwen1.5-14B-Chat',
            trust_remote_code=True,
        )
rms_norm_eps = hf_config.layer_norm_epsilon

```
报错信息:
```

Traceback (most recent call last):
  File "/home/powerop/work/rwq/TensorRT-LLM/examples/qwen/build.py", line 800, in <module>
    args = parse_arguments()
  File "/home/powerop/work/rwq/TensorRT-LLM/examples/qwen/build.py", line 471, in parse_arguments
    args.rms_norm_eps = hf_config.layer_norm_epsilon
  File "/home/powerop/work/conda/envs/tensorrt/lib/python3.10/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'Qwen2Config' object has no attribute 'layer_norm_epsilon'

```

**Comment by jklj077** [comment]
The key name is changed from `layer_norm_epsilon` in Qwen to `rms_norm_eps` in Qwen1.5/2. Please report to TensorRT-LLM.

**Comment by ArlanCooper** [comment]
OK，thanks
