### ISSUE TITLE
lora训练时报错 KeyError: 'qwen2'

### ISSUE THREAD

**Issue by Lendle-King** [QwenLM/Qwen1.5#205]
**已经更新了transformer 4.37.2，但仍报错：**

Traceback (most recent call last):
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\installer_files\env\Lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\LLM\text-generation-webui-main\modules\training.py", line 530, in do_train
    target_modules=list_target_modules(model_id),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LLM\text-generation-webui-main\modules\training.py", line 345, in list_target_modules
    return model_to_lora_modules[model_id]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'qwen2'

**Comment by JustinLin610** [comment]
never had experience in training with tgw. try to use ours, llama factory, or axolotl. we don't advise tgw for training

**Comment by zzyzeyuan** [comment]
same issue

**Comment by zhl970124** [comment]
推理试了吗？ 是否报错 KeyError: 'qwen2'

**Comment by carpe1** [comment]
The code of Qwen1.5 has been in the latest Hugging face transformers and we advise you to install transformers>=4.37.0, or you might encounter the following error:  
KeyError: 'qwen2'
**You can solve it by upgrading 'transformers'**
```
pip uninstall transformers
pip install --upgrade transformers==4.37.0
```
