### ISSUE TITLE
[BUG] Qwen-14B-Chat-Int4 vllm模式报错 no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Lzzycola** [QwenLM/Qwen1.5#211]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
* [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
* [x]  我已经搜索过FAQ | I have searched FAQ
 
### 当前行为 | Current Behavior
WARNING 03-25 19:07:57 config.py:193] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 03-25 19:07:57 llm_engine.py:87] Initializing an LLM engine with config: model='/data1/gpt/models/qwen/Qwen-14B-Chat-Int4/', tokenizer='/data1/gpt/models/qwen/Qwen-14B-Chat-Int4/', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
WARNING 03-25 19:07:57 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
2024-03-25 19:08:05 | ERROR | stderr | Traceback (most recent call last):
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-03-25 19:08:05 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/runpy.py", line 86, in _run_code
2024-03-25 19:08:05 | ERROR | stderr |     exec(code, run_globals)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/fastchat/serve/vllm_worker.py", line 290, in <module>
2024-03-25 19:08:05 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 628, in from_engine_args
2024-03-25 19:08:05 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
2024-03-25 19:08:05 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 369, in _init_engine
2024-03-25 19:08:05 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 131, in __init__
2024-03-25 19:08:05 | ERROR | stderr |     self._init_cache()
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 343, in _init_cache
2024-03-25 19:08:05 | ERROR | stderr |     num_blocks = self._run_workers(
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
2024-03-25 19:08:05 | ERROR | stderr |     driver_worker_output = getattr(self.driver_worker,
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-03-25 19:08:05 | ERROR | stderr |     return func(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/worker/worker.py", line 124, in profile_num_available_blocks
2024-03-25 19:08:05 | ERROR | stderr |     self.model_runner.profile_run()
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-03-25 19:08:05 | ERROR | stderr |     return func(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 647, in profile_run
2024-03-25 19:08:05 | ERROR | stderr |     self.execute_model(seqs, kv_caches)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-03-25 19:08:05 | ERROR | stderr |     return func(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 582, in execute_model
2024-03-25 19:08:05 | ERROR | stderr |     hidden_states = model_executable(
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 242, in forward
2024-03-25 19:08:05 | ERROR | stderr |     hidden_states = self.transformer(input_ids, positions, kv_caches,
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 210, in forward
2024-03-25 19:08:05 | ERROR | stderr |     hidden_states, residual = layer(
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 165, in forward
2024-03-25 19:08:05 | ERROR | stderr |     hidden_states = self.attn(
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 116, in forward
2024-03-25 19:08:05 | ERROR | stderr |     qkv, _ = self.c_attn(hidden_states)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-03-25 19:08:05 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 215, in forward
2024-03-25 19:08:05 | ERROR | stderr |     output_parallel = self.linear_method.apply_weights(
2024-03-25 19:08:05 | ERROR | stderr |   File "/home/deep/.conda/envs/qwen/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/gptq.py", line 206, in apply_weights
2024-03-25 19:08:05 | ERROR | stderr |     output = ops.gptq_gemm(reshaped_x, weights["qweight"],
2024-03-25 19:08:05 | ERROR | stderr | RuntimeError: CUDA error: no kernel image is available for execution on the device
2024-03-25 19:08:05 | ERROR | stderr | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2024-03-25 19:08:05 | ERROR | stderr | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2024-03-25 19:08:05 | ERROR | stderr | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2024-03-25 19:08:05 | ERROR | stderr | 

### 期望行为 | Expected Behavior
 _No response_

 
### 运行环境 | Environment
```
- OS: ubuntu 18
- Python: 3.10
- Transformers: 
- PyTorch: 2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
- Gpu: Tesla P40 24G * 2
```
 
 ### 备注 | Anything else?
根据报错信息查看了部分同样错误的解决方案，部分说显卡算力无法匹配torch 2.1 实际上简单测试过，可以加速，无报错。
另外部分说显存溢出，为此使用单张无负载显卡部署，运行至占用9G显存后即报错，根据情况判断不是显存不够的问题

**Comment by Lzzycola** [comment]
sry, forgot its 1.5B
