### ISSUE TITLE
微调AWQ量化版本的时候报错: awq_ext 未找到

### ISSUE THREAD

**Issue by 312shan** [QwenLM/Qwen1.5#221]
```
File "/usr/local/lib/python3.10/dist-packages/awq/modules/linear/gemm.py", line 66, in backward
    if awq_ext is None:
NameError: name 'awq_ext' is not defined
  0%|
```

请问是 awq 的版本的原因吗？以下是我当前版本
```
autoawq                       0.2.4
autoawq_kernels               0.0.6
```

**Comment by jklj077** [comment]
The error (`NameError`) itself is caused by buggy code in `auto-awq`. The root cause appears to be the failure in importing the `awq_ext` module.

Please first check if the requirements at <https://github.com/casper-hansen/AutoAWQ_kernels#requirements> are met and if you can successfully run `python -c "import awq_ext"`.

**Comment by LexieeWei** [comment]
@312shan 请问是否解决了，我遇到一样的问题

**Comment by Cppowboy** [comment]
遇到同样的问题，请问有解决办法吗？

**Comment by codeman0987** [comment]
在微调awq量化模型时同样遇到这个问题

**Comment by RanchiZhao** [comment]
same issue

**Comment by RicardoHalak** [comment]
same issue

**Comment by RanchiZhao** [comment]
solved, do below instead of `pip install autoawq-kernels`:
```
git clone https://github.com/casper-hansen/AutoAWQ_kernels
cd AutoAWQ_kernels
pip install -e .
```

**Comment by ArlanCooper** [comment]
> solved, do below instead of `pip install autoawq-kernels`:
> 
> ```
> git clone https://github.com/casper-hansen/AutoAWQ_kernels
> cd AutoAWQ_kernels
> pip install -e .
> ```

i can not install like this, when I  ran the code, I got this error:
```

 error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [76 lines of output]
        Building AutoAWQ Kernels version 0.0.7+cu121
        running develop
        /home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************

        !!
          easy_install.initialize_options(self)
        /home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************

        !!
          self.initialize_options()
        running egg_info
        writing autoawq_kernels.egg-info/PKG-INFO
        writing dependency_links to autoawq_kernels.egg-info/dependency_links.txt
        writing requirements to autoawq_kernels.egg-info/requires.txt
        writing top-level names to autoawq_kernels.egg-info/top_level.txt
        reading manifest file 'autoawq_kernels.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'autoawq_kernels.egg-info/SOURCES.txt'
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/powerop/work/rwq/myoperate/AutoAWQ_kernels/setup.py", line 248, in <module>
            setup(
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
            return distutils.core.setup(**attrs)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
            return run_commands(dist)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
            dist.run_commands()
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
            super().run_command(command)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/command/develop.py", line 111, in install_for_development
            self.run_command('build_ext')
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
            super().run_command(command)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
            _build_ext.run(self)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
            self.build_extensions()
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 522, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "/home/powerop/work/conda/envs/swift/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 417, in _check_cuda_version
            raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
        RuntimeError:
        The detected CUDA version (11.8) mismatches the version that was used to compile
        PyTorch (12.1). Please make sure to use the same CUDA versions.

        [end of output]

```
