### ISSUE TITLE
 Failed to import transformers.models.qwen2.modeling_qwen2

### ISSUE THREAD

**Issue by lhtpluto** [QwenLM/Qwen1.5#23]
(https://github.com/QwenLM/Qwen1.5#-hugging-face-transformers)  使用这个运行程序后，出现异常

(qwen1.5) root@test:/home/test/qwen1.5# python chat.py
Traceback (most recent call last):
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 49, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/qwen1.5/chat.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 740, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 754, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 698, in getattribute_from_module
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1354, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.qwen2.modeling_qwen2 because of the following error (look up to see its traceback):
/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
(qwen1.5) root@test:/home/test/qwen1.5#



(qwen1.5) root@test:/home/test/qwen1.5# pip list
Package                       Version
----------------------------- -----------
accelerate                    0.24.1
altair                        5.2.0
attrs                         23.2.0
blinker                       1.7.0
cachetools                    5.3.2
certifi                       2024.2.2
charset-normalizer            3.3.2
click                         8.1.7
einops                        0.7.0
filelock                      3.13.1
flash-attn                    2.5.0
fsspec                        2024.2.0
gitdb                         4.0.11
GitPython                     3.1.41
huggingface-hub               0.20.3
idna                          3.6
importlib-metadata            6.11.0
Jinja2                        3.1.3
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
mdurl                         0.1.2
mpmath                        1.3.0
networkx                      3.2.1
ninja                         1.11.1.1
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
packaging                     23.2
pandas                        2.2.0
Pillow                        9.5.0
pip                           23.3.1
protobuf                      4.25.2
psutil                        5.9.8
pyarrow                       15.0.0
pydeck                        0.8.1b0
Pygments                      2.17.2
Pympler                       1.0.1
python-dateutil               2.8.2
pytz                          2024.1
pytz-deprecation-shim         0.1.0.post0
PyYAML                        6.0.1
referencing                   0.33.0
regex                         2023.12.25
requests                      2.31.0
rich                          13.7.0
rpds-py                       0.17.1
safetensors                   0.4.2
setuptools                    68.2.2
six                           1.16.0
smmap                         5.0.1
some-package                  0.1
streamlit                     1.24.0
sympy                         1.12
tenacity                      8.2.3
tokenizers                    0.15.1
toml                          0.10.2
toolz                         0.12.1
torch                         2.2.0
torchaudio                    2.2.0
torchvision                   0.17.0
tornado                       6.4
tqdm                          4.66.1
transformers                  4.37.2
transformers-stream-generator 0.0.4
triton                        2.2.0
typing_extensions             4.9.0
tzdata                        2023.4
tzlocal                       4.3.1
urllib3                       2.2.0
validators                    0.22.0
watchdog                      4.0.0
wheel                         0.41.2
zipp                          3.17.0


(qwen1.5) root@test:/home/test/qwen1.5# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


Wed Feb  7 14:39:58 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
| 34%   55C    P2             344W / 450W |    698MiB / 24564MiB |     94%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by lhtpluto** [comment]
> (https://github.com/QwenLM/Qwen1.5#-hugging-face-transformers) 使用这个运行程序后，出现异常
> 
> (qwen1.5) root@test:/home/test/qwen1.5# python chat.py Traceback (most recent call last): File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1364, in _get_module return importlib.import_module("." + module_name, self.**name**) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 49, in from flash_attn import flash_attn_func, flash_attn_varlen_func File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn/**init**.py", line 3, in from flash_attn.flash_attn_interface import ( File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 10, in import flash_attn_2_cuda as flash_attn_cuda ImportError: /root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/test/qwen1.5/chat.py", line 4, in model = AutoModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained model_class = _get_model_class(config, cls._model_mapping) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class supported_models = model_mapping[type(config)] ~~~~~~~~~~~~~^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 740, in **getitem** return self._load_attr_from_module(model_type, model_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 754, in _load_attr_from_module return getattribute_from_module(self._modules[module_name], attr) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 698, in getattribute_from_module if hasattr(module, attr): ^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1354, in **getattr** module = self._get_module(self._class_to_module[name]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1366, in _get_module raise RuntimeError( RuntimeError: Failed to import transformers.models.qwen2.modeling_qwen2 because of the following error (look up to see its traceback): /root/anaconda3/envs/qwen1.5/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE (qwen1.5) root@test:/home/test/qwen1.5#
> 
> (qwen1.5) root@test:/home/test/qwen1.5# pip list Package Version
> 
> accelerate 0.24.1 altair 5.2.0 attrs 23.2.0 blinker 1.7.0 cachetools 5.3.2 certifi 2024.2.2 charset-normalizer 3.3.2 click 8.1.7 einops 0.7.0 filelock 3.13.1 flash-attn 2.5.0 fsspec 2024.2.0 gitdb 4.0.11 GitPython 3.1.41 huggingface-hub 0.20.3 idna 3.6 importlib-metadata 6.11.0 Jinja2 3.1.3 jsonschema 4.21.1 jsonschema-specifications 2023.12.1 markdown-it-py 3.0.0 MarkupSafe 2.1.5 mdurl 0.1.2 mpmath 1.3.0 networkx 3.2.1 ninja 1.11.1.1 numpy 1.26.4 nvidia-cublas-cu12 12.1.3.1 nvidia-cuda-cupti-cu12 12.1.105 nvidia-cuda-nvrtc-cu12 12.1.105 nvidia-cuda-runtime-cu12 12.1.105 nvidia-cudnn-cu12 8.9.2.26 nvidia-cufft-cu12 11.0.2.54 nvidia-curand-cu12 10.3.2.106 nvidia-cusolver-cu12 11.4.5.107 nvidia-cusparse-cu12 12.1.0.106 nvidia-nccl-cu12 2.19.3 nvidia-nvjitlink-cu12 12.3.101 nvidia-nvtx-cu12 12.1.105 packaging 23.2 pandas 2.2.0 Pillow 9.5.0 pip 23.3.1 protobuf 4.25.2 psutil 5.9.8 pyarrow 15.0.0 pydeck 0.8.1b0 Pygments 2.17.2 Pympler 1.0.1 python-dateutil 2.8.2 pytz 2024.1 pytz-deprecation-shim 0.1.0.post0 PyYAML 6.0.1 referencing 0.33.0 regex 2023.12.25 requests 2.31.0 rich 13.7.0 rpds-py 0.17.1 safetensors 0.4.2 setuptools 68.2.2 six 1.16.0 smmap 5.0.1 some-package 0.1 streamlit 1.24.0 sympy 1.12 tenacity 8.2.3 tokenizers 0.15.1 toml 0.10.2 toolz 0.12.1 torch 2.2.0 torchaudio 2.2.0 torchvision 0.17.0 tornado 6.4 tqdm 4.66.1 transformers 4.37.2 transformers-stream-generator 0.0.4 triton 2.2.0 typing_extensions 4.9.0 tzdata 2023.4 tzlocal 4.3.1 urllib3 2.2.0 validators 0.22.0 watchdog 4.0.0 wheel 0.41.2 zipp 3.17.0
> 
> (qwen1.5) root@test:/home/test/qwen1.5# nvcc -V nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Tue_Aug_15_22:02:13_PDT_2023 Cuda compilation tools, release 12.2, V12.2.140 Build cuda_12.2.r12.2/compiler.33191640_0
> 
> Wed Feb 7 14:39:58 2024 +---------------------------------------------------------------------------------------+ | NVIDIA-SMI 545.23.08 Driver Version: 545.23.08 CUDA Version: 12.3 | |-----------------------------------------+----------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+======================+======================| | 0 NVIDIA GeForce RTX 4090 On | 00000000:01:00.0 Off | Off | | 34% 55C P2 344W / 450W | 698MiB / 24564MiB | 94% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+

installed flash-attn-2.5.2（卸载2.5.0） 后问题解决
