### ISSUE TITLE
报错KeyError: 'qwen2_moe'

### ISSUE THREAD

**Issue by lukeewin** [QwenLM/Qwen1.5#266]
# 1. 运行环境：
OS: Windows 11
Python: 3.11
PyTorch: 2.1.0
Transformers: 4.39.3
模型使用的是：Qwen1.5-MoE-A2.7B （模型是通过git克隆到本地后使用的）

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
device = "cuda" # the device to load the model onto
model_path = r"D:\Works\Python\qwen\model\Qwen1.5-MoE-A2.7B"

model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name_or_path=model_path,
    torch_dtype="auto",
    device_map="auto",
    local_files_only=True
)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_path)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
```

# 2. 报错
Traceback (most recent call last):
  File "D:\Software\office\python\Anaconda\envs\qwen\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1155, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\office\python\Anaconda\envs\qwen\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 852, in __getitem__
    raise KeyError(key)
KeyError: 'qwen2_moe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Works\Python\qwen\top\lukeewin\qwen\main.py", line 5, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\office\python\Anaconda\envs\qwen\Lib\site-packages\transformers\models\auto\auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\office\python\Anaconda\envs\qwen\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1157, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `qwen2_moe` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by jklj077** [comment]
<https://qwenlm.github.io/blog/qwen-moe/#develop-with-qwen15-moe>

Please follow the instructions and install from the main branch of the transformers GitHub repository or wait for the release.
