### ISSUE TITLE
vllm  运行 Qwen1.5-14B-Chat 报错  TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by boboyunz** [QwenLM/Qwen1.5#36]
![image](https://github.com/QwenLM/Qwen1.5/assets/45583988/dbdd580e-b5a0-4af9-9d74-9ae11980b2b2)

python3  -m vllm.entrypoints.openai.api_server --model /root/Qwen1.5-14B-Chat
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 25, in <module>
    from vllm.entrypoints.openai.serving_completion import OpenAIServingCompletion
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/serving_completion.py", line 22, in <module>
    TypeTokenIDs = list[int]
TypeError: 'type' object is not subscriptable

**Comment by LucienShui** [comment]
`python 3.8` 及以下版本不支持这个语法，建议 `python 3.10` 及以上。
