### ISSUE TITLE
[BUG] <title>Could not get Gradio config from，现在所有的模型似乎不再支持API调用了？？不管是达摩还是HF

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [QwenLM/Qwen1.5#365]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

现在所有的模型似乎不再支持API调用了？？不管是达摩还是HF？
client = Client("https://modelscope.cn/api/v1/studio/qwen/Qwen1.5-110B-Chat-demo/gradio/", serialize=False)

出现一下报错：
```
Loaded as API: https://modelscope.cn/api/v1/studio/qwen/Qwen1.5-110B-Chat-demo/gradio/ ✔
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio_client\client.py", line 607, in _get_config
    config = json.loads(result.group(1))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "E:\Anaconda0\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-3b0d8f27ce58>", line 1, in <cell line: 1>
    client = Client("https://modelscope.cn/api/v1/studio/qwen/Qwen1.5-110B-Chat-demo/gradio/", serialize=False)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio_client\client.py", line 129, in __init__
    self.config = self._get_config()
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\gradio_client\client.py", line 609, in _get_config
    raise ValueError(
ValueError: Could not get Gradio config from: https://modelscope.cn/api/v1/studio/qwen/Qwen1.5-110B-Chat-demo/gradio/


```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by xiaolvtongxue-zt** [comment]
> `api_open=False` still allows you to make requests. It is to prevent people from skipping the queue and overloading the backend API.
> 
> **The Gradio API at ModelScope requires Authentication.**
> 
> 1. Sign in with your ModelScope account. Obtain the Cookie. Search the web if you need detailed instructions on obtaining the cookie.
> 2. Provide the cookie in `headers` when initializing the client:
>    ```python
>    from gradio_client import Client
>    headers = {"Cookie": cookie}
>    client = Client("https://www.modelscope.cn/api/v1/studio/qwen/Qwen1.5-110B-Chat-demo/gradio/", headers=headers)
>    ```
> 
> ![image](https://private-user-images.githubusercontent.com/17811943/326690499-2297100e-a342-44ed-a89e-619ce10ea649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NTk1MzEsIm5iZiI6MTcxNDQ1OTIzMSwicGF0aCI6Ii8xNzgxMTk0My8zMjY2OTA0OTktMjI5NzEwMGUtYTM0Mi00NGVkLWE4OWUtNjE5Y2UxMGVhNjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA2NDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMWEzNDQzM2ExM2QzZjI2NTI3OWE0MWM3MGQ5M2E0NjAzOTMwZDNkZDEzMDg4MzQ3MjY4ZDgwZjc1NjBlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paGPoNLVJZBjM4fq46aIAqpALZPPmZQNk1jDZKoMiu4)

感谢老师的指导，按照这个方法，可以正常调用了，非常感谢~~
