### ISSUE TITLE
qwen1.5-7B-Chat模型finetune报错

### ISSUE THREAD

**Issue by Maxhyl** [QwenLM/Qwen1.5#433]
环境：8*A100
python 3.10
torch2.2.1
cuda12.1

根据readme生成了数据集，，运行bash finetune.sh后报错如下：
  warnings.warn(
Traceback (most recent call last):
  File "/home/edcuser/models/Qwen/Qwen1.5/examples/sft/finetune.py", line 385, in <module>
    train()
  File "/home/edcuser/models/Qwen/Qwen1.5/examples/sft/finetune.py", line 376, in train
Traceback (most recent call last):
  File "/home/edcuser/models/Qwen/Qwen1.5/examples/sft/finetune.py", line 385, in <module>
Traceback (most recent call last):
      File "/home/edcuser/models/Qwen/Qwen1.5/examples/sft/finetune.py", line 385, in <module>
trainer.train()
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/trainer.py", line 3161, in compute_loss
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1736, in forward
outputs = model(**inputs)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
        return forward_call(*args, **kwargs)
loss = self.module(*inputs, **kwargs)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
      File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    loss = self.compute_loss(model, inputs)ret_val = func(*args, **kwargs)
      File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/trainer.py", line 3161, in compute_loss

return self._call_impl(*args, **kwargs)  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1736, in forward
RuntimeError
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 160, in apply_rotary_pos_emb
: indices should be either on cpu or on the same device as the indexed tensor (cpu)
        cos = cos[position_ids].unsqueeze(unsqueeze_dim)
RuntimeErrorhidden_states, self_attn_weights, present_key_value = self.self_attn(
:   File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
indices should be either on cpu or on the same device as the indexed tensor (cpu)    
return self._call_impl(*args, **kwargs)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 671, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 160, in apply_rotary_pos_emb
    result = forward_call(*args, **kwargs)    cos = cos[position_ids].unsqueeze(unsqueeze_dim)

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 671, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/home/edcuser/.conda/envs/cuda123_torch221/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 160, in apply_rotary_pos_emb
    cos = cos[position_ids].unsqueeze(unsqueeze_dim)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by jklj077** [comment]
Hi, 

```
indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
That line in the error log suggests that `cos` is on CPU and `position_ids` is on GPU, which should not happen. 

Could you list the versions of `deepspeed` and `accelerate`? Try updating those in the related environment:
```bash
pip install -U deepspeed accelerate
```

**Comment by Maxhyl** [comment]
accelerate 的版本是0.28.0
deepspeed是0.9.3
要更新到最新的版本吗？

**Comment by jklj077** [comment]
Hi, that specific version of deepspeed is incompatible ([issue](https://www.github.com/microsoft/DeepSpeed/issues/3678), anothor [issue](https://www.github.com/huggingface/transformers/issues/24040)). You can choose rolling back to 0.9.2 or upgrading to latest. You should upgrade, though. The command is provided in the previous comment.

**Comment by Maxhyl** [comment]
> Hi, that specific version of deepspeed is incompatible ([issue](https://www.github.com/microsoft/DeepSpeed/issues/3678), anothor [issue](https://www.github.com/huggingface/transformers/issues/24040)). You can choose rolling back to 0.9.2 or upgrading to latest. You should upgrade, though. The command is provided in the previous comment.

谢谢，升级到0.14.0可解决。
