### ISSUE TITLE
Error: qwen1.5-4b finetune.py

### ISSUE THREAD

**Issue by xschen-beb** [QwenLM/Qwen1.5#434]
python==3.10
torch==2.3.0+cu118
transformers==4.37.2
error：KeyError: 'qwen2'

#### error log for running finetune.sh：
Traceback (most recent call last):
  File "/cognitive_comp/Qwen1.5/examples/sft/finetune.py", line 423, in <module>
    train()
  File "/cognitive_comp/Qwen1.5/examples/sft/finetune.py", line 344, in train
    config = transformers.AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/qwen/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1022, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/qwen/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 723, in __getitem__
    raise KeyError(key)
KeyError: 'qwen2'

**Comment by jklj077** [comment]
Hi, please double check the version of `transformers`. Based on the error log, you were still using v4.32.x, and line 723 of configuration_auto.py in v4.37.2 should look like [this](https://github.com/huggingface/transformers/blob/v4.37.2/src/transformers/models/auto/configuration_auto.py#L723).
