### ISSUE TITLE
Qwen1.5-14B-Chat-GPTQ-Int4，知识库问答，被截断

### ISSUE THREAD

**Issue by KevinFanng** [QwenLM/Qwen1.5#441]
模型：Qwen1.5-14B-Chat-GPTQ-Int4
RAG:==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35.
python版本：3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35
显存：24G

匹配知识条数：默认是3，能正常运行。
调到20，就报错了。估计是某个参数超值了。

![image](https://github.com/QwenLM/Qwen1.5/assets/85269058/4cb5a851-4ede-4def-af5d-83ffb32a0212)
报错：
2024-05-27 16:46:10 | INFO | stdout | INFO:     127.0.0.1:36116 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-05-27 16:46:10,711 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-05-27 16:46:10 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-05-27 16:46:14,955 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/mnt/workspace/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 522, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/opt/conda/envs/lc/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-05-27 16:46:14,958 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by jklj077** [comment]
Please kindly direct your issue to langchain or fastchat maintainers for their assistance.
