### ISSUE TITLE
VLLM部署Qwen1.5-32B-Chat-GPTQ-Int4，总是说CUDA out of memory，但实际cuda内存是足够的

### ISSUE THREAD

**Issue by 52phm** [QwenLM/Qwen1.5#458]
运行代码
```python
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
import torch

model_path2 = "/home/xxx/llm/Qwen1.5-32B-Chat-GPTQ-Int4"
# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path2)

# Pass the default decoding hyperparameters of Qwen1.5-7B-Chat
# max_tokens is for the maximum length for generation.
sampling_params = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.05, max_tokens=512)

# Input the model name or path. Can be GPTQ or AWQ models.
llm = LLM(model=model_path2,
          max_model_len=100,
          tensor_parallel_size=2,
          # enforce_eager=True,
          gpu_memory_utilization=0.80,
          # temperature=0.2,
          # top_p=0.95,
          # max_tokens=100,
# quantization="gptq",enforce_eager=True, device='cuda:6'
          # torch_dtype="auto",
          # device_map='auto',  # auto
            # trust_remote_code=True
         )
# Prepare your prompts
prompt = "如何学习python？"
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

# generate outputs
outputs = llm.generate([text], sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

显卡信息
```bash 
+-------------------------------+----------------------+----------------------+
|   8  NVIDIA A100-PCI...  Off  | 00000000:C1:00.0 Off |                    0 |
| N/A   26C    P0    32W / 250W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   9  NVIDIA A100-PCI...  Off  | 00000000:C2:00.0 Off |                    0 |
| N/A   25C    P0    30W / 250W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

运行报错信息
```python
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 05-30 19:58:47 config.py:177] The model is convertible to Marlin format. Using Marlin kernel.
2024-05-30 19:58:50,891	INFO worker.py:1749 -- Started a local Ray instance.
INFO 05-30 19:58:52 llm_engine.py:100] Initializing an LLM engine (v0.4.2) with config: model='/home/xxx/llm/Qwen1.5-14B-Chat-GPTQ-Int4', speculative_config=None, tokenizer='/home/xxx/llm/Qwen1.5-14B-Chat-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=100, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=gptq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/home/xxx/llm/Qwen1.5-14B-Chat-GPTQ-Int4)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 05-30 19:58:56 utils.py:660] Found nccl from library /home/xxx/.config/vllm/nccl/cu11/libnccl.so.2.18.1
(RayWorkerWrapper pid=22033) INFO 05-30 19:58:56 utils.py:660] Found nccl from library /home/xxx/.config/vllm/nccl/cu11/libnccl.so.2.18.1
INFO 05-30 19:58:57 selector.py:27] Using FlashAttention-2 backend.
(RayWorkerWrapper pid=22033) INFO 05-30 19:58:58 selector.py:27] Using FlashAttention-2 backend.
INFO 05-30 19:59:01 pynccl_utils.py:43] vLLM is using nccl==2.18.1
[rank0]:[W ProcessGroupGloo.cpp:721] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
(RayWorkerWrapper pid=22033) [rank1]:[W ProcessGroupGloo.cpp:721] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
(RayWorkerWrapper pid=22033) INFO 05-30 19:59:01 pynccl_utils.py:43] vLLM is using nccl==2.18.1
INFO 05-30 19:59:02 utils.py:132] reading GPU P2P access cache from /home/xxx/.config/vllm/gpu_p2p_access_cache_for_0,1.json
(RayWorkerWrapper pid=22033) INFO 05-30 19:59:02 utils.py:132] reading GPU P2P access cache from /home/xxx/.config/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 05-30 19:59:05 model_runner.py:175] Loading model weights took 4.6527 GB
(RayWorkerWrapper pid=22033) INFO 05-30 19:59:06 model_runner.py:175] Loading model weights took 4.6527 GB
INFO 05-30 19:59:08 distributed_gpu_executor.py:45] # GPU blocks: 4101, # CPU blocks: 655
ERROR 05-30 19:59:08 worker_base.py:145] Error executing method initialize_cache. This might cause deadlock in distributed execution.
ERROR 05-30 19:59:08 worker_base.py:145] Traceback (most recent call last):
ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
ERROR 05-30 19:59:08 worker_base.py:145]     return executor(*args, **kwargs)
ERROR 05-30 19:59:08 worker_base.py:145]            ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py", line 179, in initialize_cache
ERROR 05-30 19:59:08 worker_base.py:145]     self._init_cache_engine()
ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py", line 184, in _init_cache_engine
ERROR 05-30 19:59:08 worker_base.py:145]     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
ERROR 05-30 19:59:08 worker_base.py:145]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 49, in __init__
ERROR 05-30 19:59:08 worker_base.py:145]     self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
ERROR 05-30 19:59:08 worker_base.py:145]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 64, in _allocate_kv_cache
ERROR 05-30 19:59:08 worker_base.py:145]     torch.empty(kv_cache_shape,
ERROR 05-30 19:59:08 worker_base.py:145] torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 642.00 MiB. GPU 
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145] Error executing method initialize_cache. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145] Traceback (most recent call last):
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py", line 179, in initialize_cache
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]     self._init_cache_engine()
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py", line 184, in _init_cache_engine
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 49, in __init__
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]     self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]   File "/home/xxx/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py", line 64, in _allocate_kv_cache
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145]     torch.empty(kv_cache_shape,
(RayWorkerWrapper pid=22033) ERROR 05-30 19:59:08 worker_base.py:145] torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 642.00 MiB. GPU  has a total capacity of 39.59 GiB of which 268.19 MiB is free. Process 436382 has 25.77 GiB memory in use. Including non-PyTorch memory, this process has 13.55 GiB memory in use. Of the allocated memory 11.56 GiB is allocated by PyTorch, and 61.04 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[1], line 14
     11 sampling_params = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.05, max_tokens=512)
     13 # Input the model name or path. Can be GPTQ or AWQ models.
---> 14 llm = LLM(model=model_path2,
     15           max_model_len=100,
     16           tensor_parallel_size=2,
     17           # enforce_eager=True,
     18           gpu_memory_utilization=0.80,
     19           # temperature=0.2,
     20           # top_p=0.95,
     21           # max_tokens=100,
     22 # quantization="gptq",enforce_eager=True, device='cuda:6'
     23           # torch_dtype="auto",
     24           # device_map='auto',  # auto
     25             # trust_remote_code=True
     26          ).cuda()

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/entrypoints/llm.py:123](http://17x.xx.xx.xxx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/entrypoints/llm.py#line=122), in LLM.__init__(self, model, tokenizer, tokenizer_mode, skip_tokenizer_init, trust_remote_code, tensor_parallel_size, dtype, quantization, revision, tokenizer_revision, seed, gpu_memory_utilization, swap_space, enforce_eager, max_context_len_to_capture, max_seq_len_to_capture, disable_custom_all_reduce, **kwargs)
    102     kwargs["disable_log_stats"] = True
    103 engine_args = EngineArgs(
    104     model=model,
    105     tokenizer=tokenizer,
   (...)
    121     **kwargs,
    122 )
--> 123 self.llm_engine = LLMEngine.from_engine_args(
    124     engine_args, usage_context=UsageContext.LLM_CLASS)
    125 self.request_counter = Counter()

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py:292](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py#line=291), in LLMEngine.from_engine_args(cls, engine_args, usage_context)
    289     executor_class = GPUExecutor
    291 # Create the LLM engine.
--> 292 engine = cls(
    293     **engine_config.to_dict(),
    294     executor_class=executor_class,
    295     log_stats=not engine_args.disable_log_stats,
    296     usage_context=usage_context,
    297 )
    298 return engine

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py:172](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py#line=171), in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, device_config, load_config, lora_config, vision_language_config, speculative_config, decoding_config, executor_class, log_stats, usage_context)
    157 self.generation_config_fields = _load_generation_config_dict(
    158     model_config)
    160 self.model_executor = executor_class(
    161     model_config=model_config,
    162     cache_config=cache_config,
   (...)
    169     load_config=load_config,
    170 )
--> 172 self._initialize_kv_caches()
    174 # If usage stat is enabled, collect relevant info.
    175 if is_usage_stats_enabled():

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py:262](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/engine/llm_engine.py#line=261), in LLMEngine._initialize_kv_caches(self)
    259 self.cache_config.num_gpu_blocks = num_gpu_blocks
    260 self.cache_config.num_cpu_blocks = num_cpu_blocks
--> 262 self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py:51](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py#line=50), in DistributedGPUExecutor.initialize_cache(self, num_gpu_blocks, num_cpu_blocks)
     48 self.cache_config.num_gpu_blocks = num_gpu_blocks
     49 self.cache_config.num_cpu_blocks = num_cpu_blocks
---> 51 self._run_workers("initialize_cache",
     52                   num_gpu_blocks=num_gpu_blocks,
     53                   num_cpu_blocks=num_cpu_blocks)

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py:234](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py#line=233), in RayGPUExecutor._run_workers(self, method, driver_args, driver_kwargs, all_args, all_kwargs, use_dummy_driver, max_concurrent_workers, use_ray_compiled_dag, *args, **kwargs)
    232 # Start the driver worker after all the ray workers.
    233 if not use_dummy_driver:
--> 234     driver_worker_output = self.driver_worker.execute_method(
    235         method, *driver_args, **driver_kwargs)
    236 else:
    237     assert self.driver_dummy_worker is not None

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py:146](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py#line=145), in WorkerWrapperBase.execute_method(self, method, *args, **kwargs)
    143 msg = (f"Error executing method {method}. "
    144        "This might cause deadlock in distributed execution.")
    145 logger.exception(msg)
--> 146 raise e

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py:137](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker_base.py#line=136), in WorkerWrapperBase.execute_method(self, method, *args, **kwargs)
    135     target = self if self.worker is None else self.worker
    136     executor = getattr(target, method)
--> 137     return executor(*args, **kwargs)
    138 except Exception as e:
    139     # if the driver worker also execute methods,
    140     # exceptions in the rest worker may cause deadlock in rpc like ray
    141     # see https://github.com/vllm-project/vllm/issues/3455
    142     # print the error and inform the user to solve the error
    143     msg = (f"Error executing method {method}. "
    144            "This might cause deadlock in distributed execution.")

File ~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py:179, in Worker.initialize_cache(self, num_gpu_blocks, num_cpu_blocks)
    176 self.cache_config.num_gpu_blocks = num_gpu_blocks
    177 self.cache_config.num_cpu_blocks = num_cpu_blocks
--> 179 self._init_cache_engine()
    180 self._warm_up_model()

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py:184](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/worker.py#line=183), in Worker._init_cache_engine(self)
    182 def _init_cache_engine(self):
    183     assert self.cache_config.num_gpu_blocks is not None
--> 184     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
    185                                     self.parallel_config)
    186     self.gpu_cache = self.cache_engine.gpu_cache
    187     self.model_runner.set_block_size(self.cache_engine.block_size)

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py:49](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py#line=48), in CacheEngine.__init__(self, cache_config, model_config, parallel_config)
     46 self.attn_backend = get_attn_backend(model_config.dtype)
     48 # Initialize the cache.
---> 49 self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
     50 self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")

File [~/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py:64](http://1xx.xx.xx.xx:xxx/lab/tree/llm/miniconda3/envs/qwen_env/lib/python3.11/site-packages/vllm/worker/cache_engine.py#line=63), in CacheEngine._allocate_kv_cache(self, num_blocks, device)
     61 kv_cache: List[torch.Tensor] = []
     62 for _ in range(self.num_layers):
     63     kv_cache.append(
---> 64         torch.empty(kv_cache_shape,
     65                     dtype=self.dtype,
     66                     pin_memory=pin_memory,
     67                     device=device))
     68 return kv_cache

OutOfMemoryError: CUDA out of memory. Tried to allocate 642.00 MiB. GPU

```

**Comment by jklj077** [comment]
Hi, the VRAM of the same GPU is used by two processes, which is likely a configuration issue. Please direct your issue to vllm for a more specific guidance.

**Comment by mars-ch** [comment]
Hi, I wonder how you fix your problem?
